-- Manual data backfill (not generated by drizzle-kit): copies legacy load.pickup_* / dropoff_* into load_stop before 0006 drops those columns. Do not edit this file after it has been applied to any environment.
CREATE TABLE "load_stop" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"load_id" uuid NOT NULL,
	"kind" text NOT NULL,
	"sort_order" integer NOT NULL,
	"city_zip_code" text,
	"phone" text,
	"carrier" text NOT NULL,
	"name" text NOT NULL,
	"address" text NOT NULL,
	CONSTRAINT "load_stop_load_id_kind_sort_order_uq" UNIQUE("load_id","kind","sort_order")
);
--> statement-breakpoint
ALTER TABLE "load_stop" ADD CONSTRAINT "load_stop_load_id_load_id_fk" FOREIGN KEY ("load_id") REFERENCES "public"."load"("id") ON DELETE cascade ON UPDATE no action;
--> statement-breakpoint
INSERT INTO "load_stop" ("id", "load_id", "kind", "sort_order", "city_zip_code", "phone", "carrier", "name", "address")
SELECT gen_random_uuid(), "id", 'pickup', 0, "pickup_city_zip_code", "pickup_phone", "pickup_carrier", "pickup_name", "pickup_address"
FROM "load";
--> statement-breakpoint
INSERT INTO "load_stop" ("id", "load_id", "kind", "sort_order", "city_zip_code", "phone", "carrier", "name", "address")
SELECT gen_random_uuid(), "id", 'dropoff', 0, "dropoff_city_zip_code", "dropoff_phone", "dropoff_carrier", "dropoff_name", "dropoff_address"
FROM "load";
