export const navigationLabelMap: Record<string, string> = {
  "/": "User Management",
  "/user-management": "User Management",
  "/branches": "Branch Management",
  "/loads": "Loads Management",
  "/outside-brokers": "OutSide Brokers",
  "/outside-brokers/directory": "OutSide Brokers",
  "/outside-brokers/requests": "OutSide Brokers",
  "/carriers": "Carriers",
  "/carriers/twy": "Carriers",
  "/carriers/outside": "Carriers",
  "/carriers/requests": "Carriers",
  "/accounting": "Accounting",
  "/accounting/payment-orders": "Payment Orders",
  "/accounting/external-billing": "External Billing",
  "/accounting/internal-billing": "Internal Billing",
  "/settings": "Settings",
  "/profile": "My Profile",
};
